# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: 2.1

executors:
  go:
    docker:
      - image: docker.mirror.hashicorp.services/cimg/go:1.18

jobs:
  test:
    executor:
      name: go
    steps:
      - checkout
      - run: go test

workflows:
  terraform-config-inspect:
    jobs:
      - test
